"""fix users

Revision ID: e4c6c8a3c6f8
Revises: 3e064de6f3bc
Create Date: 2022-08-07 14:27:48.763635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4c6c8a3c6f8'
down_revision = '3e064de6f3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.drop_index('login', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=100), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('login', 'users', ['login'], unique=False)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
